# Generated by Django 5.1.4 on 2026-08-03 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(default="INFO", max_length=12)),
                ("source", models.CharField(max_length=80)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_id", models.CharField(max_length=40, unique=True)),
                ("pair", models.CharField(max_length=24)),
                ("side", models.CharField(max_length=12)),
                ("exchange", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=10, max_digits=28)),
                ("price", models.DecimalField(decimal_places=10, max_digits=28)),
                (
                    "pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                ("result", models.CharField(default="Filled", max_length=24)),
                ("action", models.CharField(max_length=255)),
                ("data_mode", models.CharField(default="Live", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=160)),
                ("expertise", models.CharField(default="Beginner", max_length=32)),
                ("country", models.CharField(default="India", max_length=80)),
                ("base_currency", models.CharField(default="USD", max_length=12)),
                ("risk_profile", models.CharField(default="Balanced", max_length=32)),
                (
                    "max_trade_size",
                    models.DecimalField(decimal_places=8, default=1000, max_digits=20),
                ),
                ("exchanges", models.JSONField(default=list)),
                ("market_data_mode", models.CharField(default="Live", max_length=12)),
                ("refresh_interval", models.PositiveSmallIntegerField(default=5)),
                (
                    "maker_fee",
                    models.DecimalField(decimal_places=4, default=0.08, max_digits=8),
                ),
                (
                    "taker_fee",
                    models.DecimalField(decimal_places=4, default=0.1, max_digits=8),
                ),
                (
                    "slippage_buffer",
                    models.DecimalField(decimal_places=4, default=0.12, max_digits=8),
                ),
                (
                    "min_net_spread",
                    models.DecimalField(decimal_places=4, default=0.18, max_digits=8),
                ),
                ("paper_trading", models.BooleanField(default=True)),
                ("auto_execute", models.BooleanField(default=False)),
                ("smart_alerts", models.BooleanField(default=True)),
                ("anomaly_detection", models.BooleanField(default=True)),
                ("whale_watch", models.BooleanField(default=True)),
                ("news_sentiment", models.BooleanField(default=True)),
                (
                    "execution_preset",
                    models.CharField(default="Balanced", max_length=32),
                ),
                ("two_factor", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
